In [ ]:
# Assignment 1 

In [2]:
# Required libraries loaded
import numpy as np
import pandas as pd

In [3]:
# The table we use, 'tabulate', has been imported in order to give a more organized view to the created matrices.
!pip install tabulate
from tabulate import tabulate


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# input.txt file uploaded which includes stations and their sequence of actions. 
conveyor_capacity = [line.rstrip() for line in open('input.txt')]
print(conveyor_capacity)

['2,0,2,0,3', '-2,0,0,-1,-4']


In [5]:
# We printed the 1st item of the list to the f1 station and the 2nd item to the f2 station. However, data is listed as a string. 
f1=conveyor_capacity[0]
f2=conveyor_capacity[1]
print(f1)
print(f2)

2,0,2,0,3
-2,0,0,-1,-4


In [6]:
# numbers are listed separated by commas.
def Convert(string):
    li = list(string.split(","))
    return li
f1=Convert(f1)
f2=Convert(f2)
print(f1)
print(f2)

['2', '0', '2', '0', '3']
['-2', '0', '0', '-1', '-4']


In [7]:
#The eval function sends a string containing Python commands to the interpreter and returns the result. Converts string numbers as integers. Integer numbers are listed.
F1= [eval(i) for i in f1]
F2= [eval(i) for i in f2]
print(F1)
print(F2)

[2, 0, 2, 0, 3]
[-2, 0, 0, -1, -4]


In [8]:
zero_matrıx = np.zeros((8,5)) #An 8 by 5 zero matrix is created.Round number is 5.
count=1
#zero_matrıx[0][0]=1
carrier=8 #The number of carriers is 8.

for i in range(len(f1)): #The length of f1 is Round number which is equal to 5.
    for j in range(carrier):
        zero_matrıx[j][i]=count # The count from 1 to 5 is written into the 8 by 5 matrix. 
        count+=1
        if count==6: #If count is equal to 6, the count is set to 1 again. 
            count=1
print(zero_matrıx)

[[1. 4. 2. 5. 3.]
 [2. 5. 3. 1. 4.]
 [3. 1. 4. 2. 5.]
 [4. 2. 5. 3. 1.]
 [5. 3. 1. 4. 2.]
 [1. 4. 2. 5. 3.]
 [2. 5. 3. 1. 4.]
 [3. 1. 4. 2. 5.]]


In [9]:
# A 5 by 7 zero matrix called 'loads' is created.
loads= np.zeros((5,7))
print(loads)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [10]:

for i in range(5):
    loads[i][0]=zero_matrıx[0][i] #The 1st row of the zero matrix is written to the 1st column of the loads matrix.
    loads[i][1]=f1[int(loads[i][0])-1] #The values whose values in the f1 station correspond to the values in the 1st column of the loads matrix are written in the 2nd column.
    loads[i][2]=f2[int(loads[i][0])-1] #The values whose values in the f1 station correspond to the values in the 1st column of the loads matrix are written in the 3rd column.
    loads[0][3]=loads[0][1] #The value in the 2nd column of the 1st row is written in the 4th column. Cumulative sum is started to be made.
    loads[0][4]=loads[0][1]+loads[0][2]
    loads[0][4]=loads[0][1]+loads[0][2]    
    if i!=0: #Cumulative totals are calculated in columns 4 and 5 from top to bottom.
        loads[i][3]=loads[i][1]+loads[i-1][4]
        loads[i][4]=loads[i][3]+loads[i][2]   
        
print(loads)

[[ 1.  2. -2.  2.  0.  0.  0.]
 [ 4.  0. -1.  0. -1.  0.  0.]
 [ 2.  0.  0. -1. -1.  0.  0.]
 [ 5.  3. -4.  2. -2.  0.  0.]
 [ 3.  2.  0.  0.  0.  0.  0.]]


In [11]:
#The minimum value is calculated from the columns with cumulative totals.
a=loads[:,3:5].min() 
print(a)

-2.0


In [12]:
adjusted = np.ones((5,2)) # A matrix with all values of 1 is created.
adjusted=adjusted*abs(a) #The generated matrix is multiplied by the absolute value of the minimum value obtained.
print(adjusted)

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [13]:
loads[:,5:7]=loads[:,3:5]+adjusted #The adjusted cumulative loads values are added to the 'loads' matrix in columns 6 and 7.
print(loads)

[[ 1.  2. -2.  2.  0.  4.  2.]
 [ 4.  0. -1.  0. -1.  2.  1.]
 [ 2.  0.  0. -1. -1.  1.  1.]
 [ 5.  3. -4.  2. -2.  4.  0.]
 [ 3.  2.  0.  0.  0.  2.  2.]]


In [14]:
loads #'loads' matrix is printed.

array([[ 1.,  2., -2.,  2.,  0.,  4.,  2.],
       [ 4.,  0., -1.,  0., -1.,  2.,  1.],
       [ 2.,  0.,  0., -1., -1.,  1.,  1.],
       [ 5.,  3., -4.,  2., -2.,  4.,  0.],
       [ 3.,  2.,  0.,  0.,  0.,  2.,  2.]])

In [15]:
#It is the implementation phase of the 'tabulate' table we import earlier.
df = pd.DataFrame(loads)# The 'loads' matrix data is transferred to the dataframe.
a=['Round no.',#The titles of the table have been determined.
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df, headers = a, tablefmt = 'psql'))#Prints dataframe and headers as strings.

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       1 |            2 |           -2 |             2 |             0 |                 4 |                2 |
|           1 |       4 |            0 |           -1 |             0 |            -1 |                 2 |                1 |
|           2 |       2 |            0 |            0 |            -1 |            -1 |                 1 |                1 |
|           3 |       5 |            3 |           -4 |             2 |            -2 |                 4 |                0 |
|           4 |       3 |            2 |            0 |             0 |             0 |                 2 |    

In [16]:
#2nd sequence of actions are listed.
loads2= np.zeros((5,7))
for i in range(5):
    loads2[i][0]=zero_matrıx[1][i]
    loads2[i][1]=f1[int(loads2[i][0])-1]
    loads2[i][2]=f2[int(loads2[i][0])-1]
    loads2[0][3]=loads2[0][1] 
    loads2[0][4]=loads2[0][1]+loads2[0][2]
    #loads[i+1][3]=loads[i][4]+loads[i+1][1]
    loads2[0][4]=loads2[0][1]+loads2[0][2]    
    if i!=0:
        loads2[i][3]=loads2[i][1]+loads2[i-1][4]
        loads2[i][4]=loads2[i][3]+loads2[i][2]        
print(loads2)
a=loads2[:,3:5].min()
print(a)

adjusted2 = np.ones((5,2))
adjusted2=adjusted2*abs(a)
print(adjusted2)

loads2[:,5:7]=loads2[:,3:5]+adjusted2
print(loads2)

df2 = pd.DataFrame(loads2)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df2, headers = a, tablefmt = 'psql'))

[[ 2.  0.  0.  0.  0.  0.  0.]
 [ 5.  3. -4.  3. -1.  0.  0.]
 [ 3.  2.  0.  1.  1.  0.  0.]
 [ 1.  2. -2.  3.  1.  0.  0.]
 [ 4.  0. -1.  1.  0.  0.  0.]]
-1.0
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 2.  0.  0.  0.  0.  1.  1.]
 [ 5.  3. -4.  3. -1.  4.  0.]
 [ 3.  2.  0.  1.  1.  2.  2.]
 [ 1.  2. -2.  3.  1.  4.  2.]
 [ 4.  0. -1.  1.  0.  2.  1.]]
+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       2 |            0 |            0 |             0 |             0 |                 1 |                1 |
|           1 |       5 |            3 |           -4 |             3 |            -1 |                 4 |                0 |
| 

In [17]:
#3rd sequence of actions are listed.
loads3= np.zeros((5,7))
for i in range(5):
    loads3[i][0]=zero_matrıx[2][i]
    loads3[i][1]=f1[int(loads3[i][0])-1]
    loads3[i][2]=f2[int(loads3[i][0])-1]
    loads3[0][3]=loads3[0][1] 
    loads3[0][4]=loads3[0][1]+loads3[0][2]
    #loads[i+1][3]=loads[i][4]+loads[i+1][1]
    loads3[0][4]=loads3[0][1]+loads3[0][2]    
    if i!=0:
        loads3[i][3]=loads3[i][1]+loads3[i-1][4]
        loads3[i][4]=loads3[i][3]+loads3[i][2]        
print(loads3)
a=loads3[:,3:5].min()
print(a)

adjusted3 = np.ones((5,2))
adjusted3=adjusted3*abs(a)
print(adjusted3)

loads3[:,5:7]=loads3[:,3:5]+adjusted3
print(loads3)

df3 = pd.DataFrame(loads3)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df3, headers = a, tablefmt = 'psql'))

[[ 3.  2.  0.  2.  2.  0.  0.]
 [ 1.  2. -2.  4.  2.  0.  0.]
 [ 4.  0. -1.  2.  1.  0.  0.]
 [ 2.  0.  0.  1.  1.  0.  0.]
 [ 5.  3. -4.  4.  0.  0.  0.]]
0.0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 3.  2.  0.  2.  2.  2.  2.]
 [ 1.  2. -2.  4.  2.  4.  2.]
 [ 4.  0. -1.  2.  1.  2.  1.]
 [ 2.  0.  0.  1.  1.  1.  1.]
 [ 5.  3. -4.  4.  0.  4.  0.]]
+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       3 |            2 |            0 |             2 |             2 |                 2 |                2 |
|           1 |       1 |            2 |           -2 |             4 |             2 |                 4 |                2 |
|  

In [18]:
#4rd sequence of actions are listed.
loads4= np.zeros((5,7))
for i in range(5):
    loads4[i][0]=zero_matrıx[3][i]
    loads4[i][1]=f1[int(loads4[i][0])-1]
    loads4[i][2]=f2[int(loads4[i][0])-1]
    loads4[0][3]=loads4[0][1] 
    loads4[0][4]=loads4[0][1]+loads4[0][2]
    #loads[i+1][3]=loads[i][4]+loads[i+1][1]
    loads4[0][4]=loads4[0][1]+loads4[0][2]    
    if i!=0:
        loads4[i][3]=loads4[i][1]+loads4[i-1][4]
        loads4[i][4]=loads4[i][3]+loads4[i][2]        

a=loads4[:,3:5].min()

adjusted4 = np.ones((5,2))
adjusted4=adjusted4*abs(a)


loads4[:,5:7]=loads4[:,3:5]+adjusted4


df4 = pd.DataFrame(loads4)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df4, headers = a, tablefmt = 'psql'))

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       4 |            0 |           -1 |             0 |            -1 |                 2 |                1 |
|           1 |       2 |            0 |            0 |            -1 |            -1 |                 1 |                1 |
|           2 |       5 |            3 |           -4 |             2 |            -2 |                 4 |                0 |
|           3 |       3 |            2 |            0 |             0 |             0 |                 2 |                2 |
|           4 |       1 |            2 |           -2 |             2 |             0 |                 4 |    

In [19]:
#5th sequence of actions are listed.
loads5= np.zeros((5,7))
for i in range(5):
    loads5[i][0]=zero_matrıx[4][i]
    loads5[i][1]=f1[int(loads5[i][0])-1]
    loads5[i][2]=f2[int(loads5[i][0])-1]
    loads5[0][3]=loads5[0][1] 
    loads5[0][4]=loads5[0][1]+loads5[0][2]
    loads5[0][4]=loads5[0][1]+loads5[0][2]    
    if i!=0:
        loads5[i][3]=loads5[i][1]+loads5[i-1][4]
        loads5[i][4]=loads5[i][3]+loads5[i][2]        

a=loads5[:,3:5].min()

adjusted5 = np.ones((5,2))
adjusted5=adjusted5*abs(a)


loads5[:,5:7]=loads5[:,3:5]+adjusted5


df5 = pd.DataFrame(loads5)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df5, headers = a, tablefmt = 'psql'))

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       5 |            3 |           -4 |             3 |            -1 |                 4 |                0 |
|           1 |       3 |            2 |            0 |             1 |             1 |                 2 |                2 |
|           2 |       1 |            2 |           -2 |             3 |             1 |                 4 |                2 |
|           3 |       4 |            0 |           -1 |             1 |             0 |                 2 |                1 |
|           4 |       2 |            0 |            0 |             0 |             0 |                 1 |    

In [20]:
#6th sequence of actions are listed.
loads6= np.zeros((5,7))
for i in range(5):
    loads6[i][0]=zero_matrıx[5][i]
    loads6[i][1]=f1[int(loads6[i][0])-1]
    loads6[i][2]=f2[int(loads6[i][0])-1]
    loads6[0][3]=loads6[0][1] 
    loads6[0][4]=loads6[0][1]+loads6[0][2]
    loads6[0][4]=loads6[0][1]+loads6[0][2]    
    if i!=0:
        loads6[i][3]=loads6[i][1]+loads6[i-1][4]
        loads6[i][4]=loads6[i][3]+loads6[i][2]        

a=loads6[:,3:5].min()

adjusted6 = np.ones((5,2))
adjusted6=adjusted6*abs(a)

loads6[:,5:7]=loads6[:,3:5]+adjusted6

df6 = pd.DataFrame(loads6)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df6, headers = a, tablefmt = 'psql'))

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       1 |            2 |           -2 |             2 |             0 |                 4 |                2 |
|           1 |       4 |            0 |           -1 |             0 |            -1 |                 2 |                1 |
|           2 |       2 |            0 |            0 |            -1 |            -1 |                 1 |                1 |
|           3 |       5 |            3 |           -4 |             2 |            -2 |                 4 |                0 |
|           4 |       3 |            2 |            0 |             0 |             0 |                 2 |    

In [21]:
#7th sequence of actions are listed.
loads7= np.zeros((5,7))
for i in range(5):
    loads7[i][0]=zero_matrıx[6][i]
    loads7[i][1]=f1[int(loads7[i][0])-1]
    loads7[i][2]=f2[int(loads7[i][0])-1]
    loads7[0][3]=loads7[0][1] 
    loads7[0][4]=loads7[0][1]+loads7[0][2]
    loads7[0][4]=loads7[0][1]+loads7[0][2]    
    if i!=0:
        loads7[i][3]=loads7[i][1]+loads7[i-1][4]
        loads7[i][4]=loads7[i][3]+loads7[i][2]        

a=loads7[:,3:5].min()

adjusted7 = np.ones((5,2))
adjusted7=adjusted7*abs(a)

loads7[:,5:7]=loads7[:,3:5]+adjusted7

df7 = pd.DataFrame(loads7)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df7, headers = a, tablefmt = 'psql'))

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       2 |            0 |            0 |             0 |             0 |                 1 |                1 |
|           1 |       5 |            3 |           -4 |             3 |            -1 |                 4 |                0 |
|           2 |       3 |            2 |            0 |             1 |             1 |                 2 |                2 |
|           3 |       1 |            2 |           -2 |             3 |             1 |                 4 |                2 |
|           4 |       4 |            0 |           -1 |             1 |             0 |                 2 |    

In [22]:
#8th sequence of actions are listed.
loads8= np.zeros((5,7))
for i in range(5):
    loads8[i][0]=zero_matrıx[7][i]
    loads8[i][1]=f1[int(loads8[i][0])-1]
    loads8[i][2]=f2[int(loads8[i][0])-1]
    loads8[0][3]=loads8[0][1] 
    loads8[0][4]=loads8[0][1]+loads8[0][2]
    loads8[0][4]=loads8[0][1]+loads8[0][2]    
    if i!=0:
        loads8[i][3]=loads8[i][1]+loads8[i-1][4]
        loads8[i][4]=loads8[i][3]+loads8[i][2]        

a=loads8[:,3:5].min()

adjusted8 = np.ones((5,2))
adjusted8=adjusted8*abs(a)

loads8[:,5:7]=loads8[:,3:5]+adjusted8

df8 = pd.DataFrame(loads8)
a=['Round no.',
   'Posi.',
    'St.1 Loads',
   'St.2 Loads',
   'St.1 Cum.L.',
   'St.2 Cum.L.',
   'St.1 Adj.Cum.L.',
   'St.2 Adj.Cum.L',
   ]
print(tabulate(df8, headers = a, tablefmt = 'psql'))

+-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------+
|   Round no. |   Posi. |   St.1 Loads |   St.2 Loads |   St.1 Cum.L. |   St.2 Cum.L. |   St.1 Adj.Cum.L. |   St.2 Adj.Cum.L |
|-------------+---------+--------------+--------------+---------------+---------------+-------------------+------------------|
|           0 |       3 |            2 |            0 |             2 |             2 |                 2 |                2 |
|           1 |       1 |            2 |           -2 |             4 |             2 |                 4 |                2 |
|           2 |       4 |            0 |           -1 |             2 |             1 |                 2 |                1 |
|           3 |       2 |            0 |            0 |             1 |             1 |                 1 |                1 |
|           4 |       5 |            3 |           -4 |             4 |             0 |                 4 |    

In [23]:
# The minimum capacities required for the system to work are defined. 
#These capacities are the value in the 1st row of the st.1 adjusted cumulative load column.
min_capacity_system_work=loads[0][5]
min_capacity_system_work1=loads2[0][5]
min_capacity_system_work2=loads3[0][5]
min_capacity_system_work3=loads4[0][5]
min_capacity_system_work4=loads5[0][5]
min_capacity_system_work5=loads6[0][5]
min_capacity_system_work6=loads7[0][5]
min_capacity_system_work7=loads8[0][5]

In [24]:
#The minimum capacity values required for the system to work are listed.
print(f"for the sequence of actions  '{zero_matrıx[0]}', the minimum capacity required for the system to operate is {min_capacity_system_work}")
print(f"for the sequence of actions  '{zero_matrıx[1]}', the minimum capacity required for the system to operate is {min_capacity_system_work1}")
print(f"for the sequence of actions  '{zero_matrıx[2]}', the minimum capacity required for the system to operate is {min_capacity_system_work2}")
print(f"for the sequence of actions  '{zero_matrıx[3]}', the minimum capacity required for the system to operate is {min_capacity_system_work3}")
print(f"for the sequence of actions  '{zero_matrıx[4]}', the minimum capacity required for the system to operate is {min_capacity_system_work4}")
print(f"for the sequence of actions  '{zero_matrıx[5]}', the minimum capacity required for the system to operate is {min_capacity_system_work5}")
print(f"for the sequence of actions  '{zero_matrıx[6]}', the minimum capacity required for the system to operate is {min_capacity_system_work6}")
print(f"for the sequence of actions  '{zero_matrıx[7]}', the minimum capacity required for the system to operate is {min_capacity_system_work7}")

for the sequence of actions  '[1. 4. 2. 5. 3.]', the minimum capacity required for the system to operate is 4.0
for the sequence of actions  '[2. 5. 3. 1. 4.]', the minimum capacity required for the system to operate is 1.0
for the sequence of actions  '[3. 1. 4. 2. 5.]', the minimum capacity required for the system to operate is 2.0
for the sequence of actions  '[4. 2. 5. 3. 1.]', the minimum capacity required for the system to operate is 2.0
for the sequence of actions  '[5. 3. 1. 4. 2.]', the minimum capacity required for the system to operate is 4.0
for the sequence of actions  '[1. 4. 2. 5. 3.]', the minimum capacity required for the system to operate is 4.0
for the sequence of actions  '[2. 5. 3. 1. 4.]', the minimum capacity required for the system to operate is 1.0
for the sequence of actions  '[3. 1. 4. 2. 5.]', the minimum capacity required for the system to operate is 2.0
